# Generated by Django 2.1.7 on 2019-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='display_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shops/display-pictures/'),
        ),
    ]
