# Generated by Django 2.1.7 on 2019-04-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shop_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(default='-', max_length=16),
        ),
        migrations.AlterField(
            model_name='shop',
            name='display_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='paytm_qr',
            field=models.ImageField(upload_to=''),
        ),
    ]
